# ===============================================================================
# Copyright 2022 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============================================================================
parameters= {
        "1": "Temperature",
        "2": "Pressure",
        "3": "Depth",
        "4": "Level: Depth to Water",
        "5": "Level: Elevation",
        "6": "Latitude",
        "7": "Longitude",
        "8": "Elevation",
        "9": "Actual Conductivity",
        "10": "Specific Conductivity",
        "11": "Resistivity",
        "12": "Salinity",
        "13": "Total Dissolved Solids",
        "14": "Density",
        "16": "Baro",
        "17": "pH",
        "18": "pH MV",
        "19": "ORP",
        "20": "DO",
        "21": "% Saturation O₂",
        "22": "NO₃⁻",
        "23": "NH₄⁺",
        "24": "Cl⁻",
        "25": "Turbidity",
        "26": "Battery Voltage",
        "28": "Flow Rate",
        "29": "Total Flow",
        "30": "Partial Pressure O₂",
        "31": "Total Suspended Solids",
        "32": "External Voltage",
        "33": "Battery Level",
        "34": "Rhodamine Concentration",
        "35": "Rhodamine Fluorescence",
        "36": "Cl⁻ mV",
        "37": "NO₃⁻ as N",
        "38": "NO₃⁻ mV",
        "39": "NH₄⁺ as N",
        "40": "NH₄⁺ mV",
        "41": "NH₃ as N",
        "42": "Σ NH₃",
        "45": "Pulse",
        "49": "Velocity",
        "50": "Chl-a Concentration",
        "51": "Chl-a Fluorescence",
        "54": "BGA-PC Concentration",
        "55": "BGA-PC Fluorescence",
        "58": "BGA-PE Concentration",
        "59": "BGA-PE Fluorescence",
        "62": "Total Flow (resettable)",
        "63": "Total Positive Flow",
        "64": "Total Positive Flow (resettable)",
        "65": "Total Negative Flow",
        "66": "Total Negative Flow (resettable)",
        "67": "Fluoroscein Concentration",
        "68": "Fluoroscein Fluorescence",
        "69": "FDOM Concentration",
        "70": "FDOM Fluorescence",
        "80": "Crude Oil Concentration",
        "81": "Crude Oil Fluorescence",
        "82": "Rainfall",
        "flowVelocity": "Flow Velocity",
        "density": "Density",
        "concentration": "Concentration"
    }

units = {
        "1": "C",
        "2": "F",
        "17": "psi",
        "19": "kPa",
        "20": "bar",
        "21": "mbar",
        "22": "mm Hg",
        "23": "in Hg",
        "24": "cm H₂O",
        "25": "in H₂O",
        "26": "torr",
        "27": "atm",
        "33": "mm",
        "34": "cm",
        "35": "m",
        "36": "km",
        "37": "in",
        "38": "ft",
        "49": "°",
        "65": "µS/cm",
        "66": "mS/cm",
        "81": "Ω-cm",
        "97": "psu",
        "113": "ppm",
        "114": "ppt",
        "117": "mg/L",
        "118": "µg/L",
        "120": "g/L",
        "121": "ppb",
        "129": "g/cm³",
        "145": "pH",
        "162": "mV",
        "163": "V",
        "177": "% sat",
        "193": "FNU",
        "194": "NTU",
        "209": "ft³/s",
        "212": "ft³/day",
        "213": "gal/s",
        "214": "gal/min",
        "215": "gal/hr",
        "216": "Mgal/day",
        "217": "m³/s",
        "219": "m³/hr",
        "221": "L/s",
        "222": "ML/d",
        "223": "mL/min",
        "224": "kL/d",
        "225": "ft³",
        "226": "gal",
        "227": "Mgal",
        "228": "m³",
        "229": "L",
        "230": "ac-ft",
        "231": "mL",
        "232": "ML",
        "233": "kL",
        "234": "ac-in",
        "241": "%",
        "257": "RFU",
        "274": "mL/hr",
        "275": "L/min",
        "276": "L/hr",
        "305": " ",
        "322": "Hz",
        "337": "ft/s",
        "338": "m/s",
        "yard": "yd",
        "acreInchPerMinute": "ac-in/min",
        "g/mL": "g/mL",
        "acreFeetPerSecond": "ac-ft/sec",
        "kilolitersPerMinute": "kL/min",
        "litersPerDay": "L/d",
        "qsu": "QSU",
        "millilitersPerSecond": "mL/s",
        "acreInchPerDay": "ac-in/d",
        "megalitersPerMinute": "ML/min",
        "acreInchPerHour": "ac-in/hr",
        "mile": "mi",
        "acreFeetPerMinute": "ac-ft/min",
        "kilolitersPerSecond": "kL/sec",
        "cubicFeetPerHour": "ft³/hr",
        "cubicMetersPerMinute": "m³/min",
        "cubicMetersPerDay": "m³/day",
        "megalitersPerSecond": "ML/sec",
        "megalitersPerHour": "ML/hr",
        "acreFeetPerDay": "ac-ft/d",
        "kilolitersPerHour": "kL/hr",
        "millilitersPerDay": "mL/day",
        "acreInchPerSecond": "ac-in/sec",
        "acreFeetPerHour": "ac-ft/hr",
        "cubicFeetPerMinute": "ft³/min",
        "kilohertz": "kHz"
    }

# ============= EOF =============================================
